/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DreamNoms (https://sketchfab.com/DreamNoms)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-low-poly-german-shepherd-18d8fbe184c5448283762893b6ea9752
Title: Stylized Low Poly German Shepherd
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from'../assets/3d/dog.glb';

const Dog = ({currentAnimation, ...props}) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)
   // This effect will run whenever the currentAnimation prop changes
   useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Lamp" position={[4.076, 1.005, 5.904]} rotation={[-0.268, 0.602, 1.931]}>
              <group name="Lamp_1" />
            </group>
            <group name="metarig" scale={9.844}>
              <primitive object={nodes.metarig_rootJoint} />
              <skinnedMesh
                name="Cube_0"
                geometry={nodes.Cube_0.geometry}
                material={materials.material}
                skeleton={nodes.Cube_0.skeleton}
              />
              <skinnedMesh
                name="Cube_1"
                geometry={nodes.Cube_1.geometry}
                material={materials.Nose}
                skeleton={nodes.Cube_1.skeleton}
              />
              <skinnedMesh
                name="Cube_2"
                geometry={nodes.Cube_2.geometry}
                material={materials.Dark}
                skeleton={nodes.Cube_2.skeleton}
              />
              <skinnedMesh
                name="Cube_3"
                geometry={nodes.Cube_3.geometry}
                material={materials.Pads}
                skeleton={nodes.Cube_3.skeleton}
              />
              <skinnedMesh
                name="Cube_4"
                geometry={nodes.Cube_4.geometry}
                material={materials.Light}
                skeleton={nodes.Cube_4.skeleton}
              />
              <group name="Cube" scale={0.102} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Dog
